language: csharp
solution: QueryStringArray.sln
mono: none
dotnet: 1.0.1
dist: trusty
branches:
  only:
    - master
before_script:
  - dotnet restore
script:
  - dotnet build -c Release
after_script:
  - dotnet pack -c Release src/O7.QueryStringArray.csproj
  - dotnet nuget push src/bin/Release/O7.QueryStringArray.1.0.0.nupkg -k $NUGET_API_KEY -s https://nuget.org/